server:
  error:
    include-stacktrace: always
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: GORBUNOV
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    generate-ddl: true
    database: postgresql
    properties:
      hibernate:
        globally_quoted_identifiers: true
        default_schema: leonardo

camunda:
  bpm:
    admin-user:
      email: sigma@gmail.com
      password: grindset
      id: sigma
      first-name: Ned
      last-name: Flanders